version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"
  postgres_marketplace:
     container_name: postgres_marketplace_ifood
     image: postgres:12.2
     environment:
       POSTGRES_USER: marketplace
       POSTGRES_PASSWORD: marketplace
     ports:
      - "5433:5432"
  keycloak_ifood:
    container_name: keycloak_ifood
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin 
      KEYCLOAK_PASSWORD: 1234567 
    ports:
    - 8180:8080   
  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.22
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "14250:14250"
    - "9411:9411"

  prometheus_ifood:
    container_name: prometheus_ifood
    image: prometheus-ifood
    ports:
      - "9090:9090"
  
  grafana_ifood:
    container_name: grafana_ifood
    image: grafana/grafana:7.5.0
    ports:
      - "3000:3000"
    
  